### ISSUE TITLE
Draft content in WP shouldn't be searchable. 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#1031] opened 2017-06-23 14:07 UTC
A search for SDG's brings up this story: https://opendevelopmentmekong.net/?s=SDG&type=story&page=0
![image](https://user-images.githubusercontent.com/14996905/27485652-ea374cac-5803-11e7-8943-52a5a1b787ca.png)

But it must be in draft on WP because the link takes you to a 404 message: 
https://opendevelopmentmekong.net/?post_type=story&p=5625502
![image](https://user-images.githubusercontent.com/14996905/27485692-1bedabba-5804-11e7-9d34-8ee7c5e7bc10.png)

**Comment by acorbi** [comment] 2017-06-26 12:43
Hi @prustar thanks for raising this. 

I am aware of this issue and have already identified the origin and solution. However there is the need for deploying the latest wp-odm_solr code on PROD in order to fix it. The latest code includes the **view ALL** area/section of the search page which in my understanding has not being completely marked as production-ready yet. I will try to gather from the others wether is OK to release the latest code into PROD which will then also fix this issue, among others.

**Comment by acorbi** [comment] 2017-06-29 15:25
Since riollout into PROD has already happened, this issue cannot be reproduced anymore.

**Closed by acorbi** 2017-06-29 15:25 UTC
