### ISSUE TITLE
MAP MENU - Thematic Map Issues

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#124] opened 2016-07-18 00:41 UTC
Clicking FRONT PAGE MAP selection
![fp-map](https://cloud.githubusercontent.com/assets/16559612/16904159/c7b96c34-4c5e-11e6-88fd-a63407ed4fbf.png)

Gets you this

![mp-dev](https://cloud.githubusercontent.com/assets/16559612/16904162/d32b7454-4c5e-11e6-80a1-9d4b71ffd969.JPG)

Clicking 

Mining Licences
Tree Cover
Interactive Map

Gets you a blank Base Map
![blankmap](https://cloud.githubusercontent.com/assets/16559612/16904184/26e16ca2-4c5f-11e6-8b2c-5388e5c840e8.JPG)

**Comment by acorbi** [comment] 2016-07-18 05:57
@Huyeng can you please help configuring the thematic maps appropiatelly on Pre-Production after you fix the cartodb bug. this would help us to showcase the thematic maps appropiately.

**Comment by gimmemochi** [comment] 2016-07-18 09:54
@acorbi @prustar **Interactive Map**, under THEMATIC MAPS, is the same as Map Explorer, right?

<img width="653" alt="screen shot 2016-07-18 at 4 51 00 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911353/300b1ffe-4d08-11e6-9d45-6106db6fc497.png">

**Comment by gimmemochi** [comment] 2016-07-18 09:59
@acorbi I saw this when clicking on "Forest Cover" thematic map: https://cambodia.pp.opendevelopmentmekong.net/km/maps/forest-cover/

<img width="1215" alt="screen shot 2016-07-18 at 4 55 31 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911418/8ae01164-4d08-11e6-8f1c-8ffc7c7f2688.png">

Also saw the same error message when clicking on **economic land concession** on the Map Catalog page (not the list of categories as presented when clicked on **WMC radio** or **Hydropower** maps in the map catalog).
https://cambodia.pp.opendevelopmentmekong.net/km/layers/economic-land-concessions-including-adjustments-to-concessions/

**Comment by gimmemochi** [comment] 2016-07-18 10:02
@acorbi I saw this when clicking on "Forest Cover" thematic map: https://cambodia.pp.opendevelopmentmekong.net/km/maps/forest-cover/

<img width="1215" alt="screen shot 2016-07-18 at 4 55 31 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911536/3d5ff458-4d09-11e6-9560-896aaeae5852.png">

**Comment by prustar** [comment] 2016-07-18 11:01
@gimmemochi The Thematic Maps are Map Explorer - I suggest we remove the 'Map Explorer' icon. It's confusing. Then all the maps should have a thematic category that the layers would fall into which would allow users to see different datasets used in more appropriate scenarios. All maps are then available in the catalogue (an existing function only now being implemented). 

@acorbi @Huyeng -- Can we get the bits to function then perhaps we can allocate some map layers to them to test what works best. The groupings for thematic layers should be: 

1. Land and Environment - i.e. forest cover, community forest etc
2. Agriculture and Fishing - i.e. areas under agriculture and the updated fishing data, census should be made available here. 
3. Economic Development (alternative suggestions welcome here) - This displays all of the profile data. Options to overlay upon forest cover and census. 
4. Hydrology - Aquaduct data, hydropower, water etc.
5. Demographics - All census, national elections, radio, infrastructure and other demographic information

There will be common base layers and also some overlap layers made available for demonstration. A category for base layers should be made available upon all the thematic areas so that infrastructure, boundaries and other standard layers be made available on each theme. 

@punwath @samean - Once these have been finalised can we chat to re-allocate the layers appropriately to the above.

**Comment by acorbi** [comment] 2016-07-19 09:06
@prustar I like your idea of transitioning from map explorer to thematic maps. As soon as me and @Huyeng finish fixing the last bugs on the mapping code we will be able to configure this appropiately.

>  A category for base layers should be made available upon all the thematic areas so that infrastructure, boundaries and other standard layers be made available on each theme. 

This is already implemented with the base layers, only configuration and finding those base layers that we will be using is still pending.

**Comment by prustar** [comment] 2016-07-19 09:15
@acorbi - Thanks I hope the end product is as compelling. In regards to base layers there's two types I'm referring to here and perhaps we should call them something different.

1. Base Layer is the 'template' background map image i.e. topography, satellite, shade relief etc. 
2. 'Group map layers' that are standardised across all thematic maps i.e. boundaries, census, infrastructure.  Perhaps we should call these something else - Standard layers?

**Comment by Huyeng** [comment] 2016-07-20 10:34
The issue is solved. Let discuss the template of thematic maps and log the new issues. 
Can i close it?

**Comment by acorbi** [comment] 2016-07-20 10:35
closing.

**Closed by acorbi** 2016-07-20 10:35 UTC
