### ISSUE TITLE
Download Maps page doesn't response 

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#348] opened 2016-09-01 04:15 UTC
When goes to https://cambodia.opendevelopmentmekong.net/layers, the site is always like in the pic below
![image](https://cloud.githubusercontent.com/assets/18112596/18155183/33138b46-7035-11e6-8cf9-8cab3fecf8f3.png)

**Comment by acorbi** [comment] 2016-09-01 06:41
@punwath I cannot reproduce it in any of my machines. Can you please provide details about your browser, OS, etc as specified in https://wiki.opendevelopmentmekong.net/public:bug_reporting. Thanks

**Comment by Huyeng** [comment] 2016-09-01 08:04
@acorbi, for the map catalogue, ODC prefer to use the template that show the caption below the Thumbnail. Thus, it is clearly to see how the map looks like and attract the users .

For the title post's link are needed to update and point to the data page instead of the single page like PP site. 
It is a bit strange to me that the both of Grid-4 column template that you and I created are working fine for the map catalogue while I was working on. It means that the link of title is update and point to data page.

**Comment by punwath** [comment] 2016-09-01 08:15
I am using Chrome version 52. When I view this page with Chrome, the page doesn't response like this picture. The page is frezzed, I cannot move up or down.

![image](https://cloud.githubusercontent.com/assets/18112596/18160208/8fdcc60a-7056-11e6-93c9-90528de22723.png)

I refreshed many times but it is still like this. Thanks

**Comment by acorbi** [comment] 2016-09-01 09:30
@punwath ok, I could reproduce this Issue in one machine using Chrome. I will look at the Issue today or tomorrow. I believe it has to do with the fact that the site loads up lots of images

@Huyeng You are raising multiple (and different) points in your comment:

1. You are making a **feature request** to change the layout of the items listed on the map catalogue. Please open a separate issue **with specific details** to focus the discussion over there.

2. You are raising a **Bug report** indicating that something is not working properly on the title links. Please open a separate issue **with specific details** to focus the discussion over there.

**Comment by Huyeng** [comment] 2016-09-02 02:51
Ok. I will do that.

**Comment by acorbi** [comment] 2016-09-05 15:51
Fixed via 17c9258468c874135abd4f7bddcc5d9f5d73c2c9. @punwath please test on PP: http://cambodia.pp.opendevelopmentmekong.net/layers and confirm that is working now.

**Closed by acorbi** 2016-09-05 15:51 UTC
