### ISSUE TITLE
Topic navigation under the Taxonomy widget error

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_theme#944] opened 2017-05-24 09:33 UTC
No clicked icon ahead of each main topic for user to view the sub-topics. Click the link here:
https://opendevelopmentcambodia.net/updates/open-development-cambodia-publishes-a-new-dataset%E2%80%8B-on-results-on-the-election-of-communesangkat-council-2012/
![screenshot_18](https://cloud.githubusercontent.com/assets/19201022/26396565/c6739640-409d-11e7-9f6f-8e1c7cff4366.png)

**Comment by acorbi** [comment] 2017-05-24 10:14
@Huyeng seems that those other links (besides Agriculture and fishing) do not have the **plusimage-cambodia** class:

![screenshot from 2017-05-24 12-12-18](https://cloud.githubusercontent.com/assets/384894/26398637/651dfbec-407a-11e7-9870-b84ae35df4a3.png)

as they should:

![screenshot from 2017-05-24 12-13-45](https://cloud.githubusercontent.com/assets/384894/26398674/7e5c5928-407a-11e7-8735-a16aa35b6007.png)

**Comment by Huyeng** [comment] 2017-05-25 03:32
It is not the caused problem. The error caused by the js script that tries to find the span element with a specific class name, but that class is no available in the taxonomy list, then error occurred.

**Comment by acorbi** [comment] 2017-05-25 10:06
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/949

**Closed by acorbi** 2017-05-25 10:06 UTC
