### ISSUE TITLE
Responsive: Header on Safari Mobile Mode

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1067] opened 2017-07-06 09:59 UTC
<img width="270" alt="screenshot at jul 06 17-01-09" src="https://user-images.githubusercontent.com/6613530/27906112-64205672-626c-11e7-8cfe-1abd1266c345.png">

**Comment by acorbi** [comment] 2017-07-06 10:07
It should render as pictured below:

![screenshot from 2017-07-06 12-06-57](https://user-images.githubusercontent.com/384894/27906417-b774810a-6243-11e7-8950-860128059846.png)

**Comment by acorbi** [comment] 2017-07-06 18:30
@Huyeng just tested on an iphone 7 and could not reproduce it. See screenshot

![index](https://user-images.githubusercontent.com/384894/27926812-fe1a04ea-6289-11e7-922b-9aee42bbdafa.jpeg)

**Comment by acorbi** [comment] 2017-07-17 13:35
@Huyeng @DragonVirus @gimmemochi @DBishton @prustar @jpeizer1 anyone with an iphone around can try to reproduce this?

**Comment by Huyeng** [comment] 2017-07-20 08:19
Before the header looks good on the Firefox responsive mobile mode, but not it shows like below:
![screenshot_2](https://user-images.githubusercontent.com/6613530/28407540-af897484-6d5e-11e7-8fcb-c969a41374d2.jpg)

**Comment by acorbi** [comment] 2017-07-20 09:21
the Firefox responsive mobile mode does not behave exactly as an iphone. Have you tested on a real device?

**Comment by acorbi** [comment] 2017-07-23 15:12
@Huyeng I just tested on an iphone 5s and could not reproduce the issue. I'm closing it, please reopen if you can reproduce it on a real device.

**Closed by acorbi** 2017-07-23 15:12 UTC
