### ISSUE TITLE
Map Explorer // Doesn't exist any more

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#498] opened 2016-10-01 07:38 UTC
I've reallocated all of the layers into separate maps so that they are easy to visualise and make more sense. However this means that the Map explorer is now blank.

Can we disable the link and just allow users to hover over MAP and force them to select a specific map? Otherwise I will move some of the layers onto the map explorer so that at least something shows up when it is selected. 

![image](https://cloud.githubusercontent.com/assets/14996905/19012597/ac67de24-87ba-11e6-95ec-1a118c9e3e76.png)

**Comment by acorbi** [comment] 2016-10-01 09:41
@prustar what is the reason behind uncategorizing ALL the published map layers on https://opendevelopmentmekong.net/wp-admin/edit.php?post_type=map-layer ? As I understand, thematic maps and map-explorer can leave together.

The expected behaviour would be that:
- **Map layers** are categorized so they appear organized on the map explorer
- **Map layers** can be added to **maps** so they can be grouped in thematic maps 
Both options should be able to co-exists....

If this is not the case, please comment. If it is, please re-categorize LL layers

**Comment by prustar** [comment] 2016-10-03 07:20
@acorbi -- The simple answer is that having both duplicates everything. What theme then is the Map explorer based upon and how do we not duplicate this over a thematic theme? 

As I had to work with this default behaviour, I curated a layer that would appear when users click on map explorer. I categorised this as a 'feature' set of layers where we could highlight new layers when they become available and then also lead to a thematic area for greater detail. An introduction page to the maps - this would need to be tweaked and would then lead onto development of this page as the main landing page for the maps - metadata - downloads. 

Unfortunately the map explorer lists the layers in the category and users need to activate the layers. Ideally we should have the same function options as in the thematic maps - that is to select layers to appear by default. Inversely the ability to categorise layers in the thematic maps is also a necessity to be able to distinguish between layers.

**Comment by acorbi** [comment] 2016-10-03 10:21
@prustar:

> The simple answer is that having both duplicates everything. 

Layers exposed on thematic maps are also available on map explorer, that is true. But uncategorizing ALL layers has no point, it just breaks the map explorer and removes important context information around the currently maintained layers. In my understanding, there are different ways of leveraging the code-base that we currently have to fit different scenarios:

- If you consider that the map explorer should not be made available to the user (on the menu), let's just hide the menu item but **let's no break existing functionality**. 

- If you consider the map explorer should expose other layers rather than those available through thematic maps (this is what you did now with that feature layer), why don't you just create a **thematic map** which contains those featured layers only?? I still see no point on uncategorizing ALL the layers thus breaking the map explorer.

> What theme then is the Map explorer based upon and how do we not duplicate this over a thematic theme? 

As I see it, the map explorer should be defined as _A web application exposing all available curated layers on our system which are made available to the user grouped by categories. The user should then be able to toggle layers to make sense of the available data as they need/want. It also functions as a information hub where the user might find links to other parts of the system (i.e Profile pages via those little table icons) and as its name describes, allows to explore available information without being embedded on a specific thematic context_ .

Thematic maps are _Micro instances of the map explorer where only layers related to a certain topic (theme) are exposed. Thematic maps allow a much more detailed analysis of data around a specific issue (i.e Water) and are suitable to be embedded on topic pages or other theme-specific contents_ 

The map explorer **should be able to co-exist with thematic maps**, and here you need to think about our partners as well. http://www.opendevelopmentcambodia.net/ had an has, a map explorer and might want to keep exposing it to their users (@huyeng you thoughts? ) through the menu.

> As I had to work with this default behaviour, I curated a layer that would appear when users click on map explorer. I categorised this as a 'feature' set of layers where we could highlight new layers when they become available and then also lead to a thematic area for greater detail.

I would not call that **map explorer**, I would not use the map explorer for that. I would call that component/module/page something like **latest layers / new layers** and implement that with a **thematic map**. 

> Unfortunately the map explorer lists the layers in the category and users need to activate the layers. Ideally we should have the same function options as in the thematic maps - that is to select layers to appear by default. Inversely the ability to categorise layers in the thematic maps is also a necessity to be able to distinguish between layers and develop a cohesive story. 

This should be approached as two **feature requests**, please report so we can discuss/project them accordingly.

Having said this, I would suggest that:

- You re-categorize all layers on ODM PROD site as they were so the map explorer is functional again.
- You remove the **feature** layer category and implement that "latest layers / new layers" component with a thematic map, if there is a use case for it.
- You discuss and decide together with @DBishton whether we want to have the map explorer being exposed from the menu or whether we just expose thematic maps.

**Comment by prustar** [comment] 2016-10-03 13:53
> As I see it, the map explorer should be defined as A web application exposing all available curated layers on our system which are made available to the user grouped by categories. The user should then be able to toggle layers to make sense of the available data as they need/want. It also functions as a information hub where the user might find links to other parts of the system (i.e Profile pages via those little table icons) and as its name describes, allows to explore available information without being embedded on a specific thematic context .

You just describe here the map catalogue. Which is still to be developed that is more powerful and allows for exposure to metadata. Using the Map explorer in this way is not appropriate as has been discussed for sometime now. The layering of 20+ layers becomes unmanageable over time which is why we have developed the thematic maps. 

> The map explorer should be able to co-exist with thematic maps, and here you need to think about our partners as well. http://www.opendevelopmentcambodia.net/ had an has, a map explorer and might want to keep exposing it to their users (@huyeng you thoughts? ) through the menu.

I've worked with ODC to develop thematic maps in upcoming proposals. It's the solution to the current mix mash of layers that currently exist without ability to curate effectively. 

> I would not call that map explorer, I would not use the map explorer for that. I would call that component/module/page something like latest layers / new layers and implement that with a thematic map.

The function is not possible. 

> Having said this, I would suggest that:

You re-categorize all layers on ODM PROD site as they were so the map explorer is functional again.
You remove the feature layer category and implement that "latest layers / new layers" component with a thematic map, if there is a use case for it.
You discuss and decide together with @DBishton whether we want to have the map explorer being exposed from the menu or whether we just expose thematic maps.

- For expediency sake I'm not going to reclassify all of the layers as I don't have time to do this and it wasn't my intent. 
- Removing the feature layer would then render the map explorer link with nothing on it so I'd rather leave something there OTHERWISE if we remove the map explorer link and leave the thematic maps then this would solve this issue. 

Please note that the thematic maps don't allow for categories so we cannot added too many layers as this will increase the conflict between layers. 


 







>

**Comment by acorbi** [comment] 2016-10-03 15:05
> You just describe here the map catalogue.

The map catalogue cannot do that yet. Let's work with the things that are currently working.

> Using the Map explorer in this way is not appropriate as has been discussed for sometime now. The layering of 20+ layers becomes unmanageable over time which is why we have developed the thematic maps. 

Agreed. However, this is not a reason for uncategorizing all those layers.

> I've worked with ODC to develop thematic maps in upcoming proposals. It's the solution to the current mix mash of layers that currently exist without ability to curate effectively. 

Agreed. However, this is not a reason for uncategorizing all those layers.

> The function is not possible. 

Not possible? That is not correct. You can just create a new map (under Maps > Add new map), call it "new layers", add the 2 or 3 new layers to it and expose it as thematic map somewhere in the UI. Correct me if I understood it wrong, but this is absolutely possible with the current code.

> For expediency sake I'm not going to reclassify all of the layers as I don't have time to do this and it wasn't my intent.

I can take over that task for you. should I?

> OTHERWISE if we remove the map explorer link and leave the thematic maps then this would solve this issue. 

then let's remove the map-explorer from the menu. But let's recategorize all those layers because honestly I do not see the point of having them uncategorized and you have not provided any requirements that make uncategorizing them unneded.

> Please note that the thematic maps don't allow for categories so we cannot added too many layers as this will increase the conflict between layers. 

Correct, that is clear and I have just logged a **feature request**: https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/499

To make my position even more clear:
- I do not see the need of uncategorizing those layers thus breaking the map explorer. So either you or me should do it but those layers should stay categorized as long as there is no major reason to uncategorize them

**Comment by prustar** [comment] 2016-10-03 15:52
@acorbi - my requirements for development of the map explorer have yet to be fully implemented. 

Please DO NOT re-categories the layers back onto the map explorer. Simply because you don't see the point doesn't mean that there isn't one. I have allocated all layers to a thematic area and they are all accessible through the dropdown Map explorer link. Every layer except those in draft are still available. 

I need to demo this on Thursday so I will live with what we have and use the thematic layers as they are. I do not want the mix mash to be available to people, so I will leave the one demo layer there as required so that if people do click on it there is something.

**Comment by acorbi** [comment] 2016-10-03 16:19
@prustar

> my requirements for development of the map explorer have yet to be fully implemented

happy to discuss and coordinate this separately. 

> Simply because you don't see the point doesn't mean that there isn't one

can you please elaborate on why uncategorizing the layers is needed? this is not the first time i am asking this on this conversation and you havent given me any solid arguments.

>  I have allocated all layers to a thematic area and they are all accessible through the dropdown Map explorer link. Every layer except those in draft are still available.
>I need to demo this on Thursday so I will live with what we have and use the thematic layers as they are

nothing against this. go for it!

>  I do not want the mix mash to be available to people, so I will leave the one demo layer there as required so that if people do click on it there is something.

I do not agree with this solution. why do not you just hide the link to the map explorer instead of changing its functionality while uncategorizing all the layers? read your initial comments on this issue. quoting your own words:

> Can we disable the link and just allow users to hover over MAP and force them to select a specific map? 

yes, we can. this is what i am proposing as solution without needing to uncategorize all those layers and breaking the map explorer...

**Comment by Huyeng** [comment] 2016-10-04 03:41
The map explorer is exposing all the published layers that categorized to show on the page.  It seems like the hub of map layers that users can interact any layers that they interested to produce the maps as they need. Thematic maps is a kind of mapping functionality that allow us to specific layers that relevant to the topics to make it easy for the users, but it doesn't mean that all the layers that listed in thematic map are all they need. Sometimes, the users may need additional layers for different purpose, so Map explorer is a place where users can add different topic layers as they need.

Yes, it is exactly that the layers exposed on thematic maps are also available on map explorer if they are published and categorize. It seems like duplicate between map explorer and thematic map, but if you change the thinking to that the thematic map is playing as the filter function of map explorer by specific topics, so it won't be duplicated. Anyways, if you don't want users to access to the map explorer, i would like to support Alex's proposing to hide/disable the link of Map menu. However, the map explorer page is still accessible through the link from google searching or bookmark.

**Comment by acorbi** [comment] 2016-10-04 07:59
thanks for your comments @Huyeng 

> However, the map explorer page is still accessible through the link from google searching or bookmark. 

Also, even if we hide it from the menu, the user is always going to be possibly landing on the map explorer while changing sites (i.e from Cambodia -> Regional). 

@prustar you are the coordinator for the data working stream and this is your responsibility to coordinate but this is currently affecting the functionality and navigability of the site. 

Again, **elaborate on an argument** on why those layers should be uncategorized (hence "breaking" the map explorer's current functionality) or please **re-categorize** them ( or leave it to me ).

**Comment by acorbi** [comment] 2016-10-04 14:07
@prustar I have just recategorized the majority of the layers on the map explorer. Closing this Issue

**Closed by acorbi** 2016-10-04 14:07 UTC
